<?php

namespace console\controllers;

use yii\console\Controller;
use common\models\Post;

// 控制台到当前目录下  ./yii hello/index
class HelloController extends Controller
{

  public $rev;
  public $r;

  public function options($actionID)
  {
    return ['rev'];
  }

  public function optionAliases()
  {
    parent::optionAliases(); // TODO: Change the autogenerated stub
    return ['r' => 'rev'];
  }

  public function actionIndex()
  {
    if ($this->rev == 1) {
      echo strrev("Hello World!") . "\n";
    } else {
      echo "Hello World \n";
    }
  }

  public function actionList()
  {
    $post = Post::find()->all();

    foreach ($post as $apost) {
      echo($apost['id'] . '-' . $apost['title'] . "\n");
    }
  }

  public function actionWho($name)
  {
    echo('Hello' . $name);
  }

  public function actionAll(array $name)
  {
    var_dump($name);
  }
}